[package]
name = "fish_torrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
urlencoding = "2.1.3"
mio = "0.8"
bendy = "^0.3"
clap = "4.4.11"
